// Map<String, dynamic> findCountryCodeByIndex(int index) {
//   return countryCodeData.firstWhere((element) => element['index'] == index);
// }

const List<Map<String, dynamic>> countryCodeData = [
  {
    'index': 0,
    'code': 'AF',
    'flag': 'af.png',
    'dial_code': '+93',
    'default_value': 'Afghanistan',
  },
  {
    'index': 1,
    'code': 'AX',
    'flag': 'ax.png',
    'dial_code': '+358',
    'default_value': 'Åland Islands',
  },
  {
    'index': 2,
    'code': 'AL',
    'flag': 'al.png',
    'dial_code': '+355',
    'default_value': 'Albania',
  },
  {
    'index': 3,
    'code': 'DZ',
    'flag': 'dz.png',
    'dial_code': '+213',
    'default_value': 'Algeria',
  },
  {
    'index': 4,
    'code': 'AS',
    'flag': 'as.png',
    'dial_code': '+1684',
    'default_value': 'American Samoa',
  },
  {
    'index': 5,
    'code': 'AD',
    'flag': 'ad.png',
    'dial_code': '+376',
    'default_value': 'Andorra',
  },
  {
    'index': 6,
    'code': 'AO',
    'flag': 'ao.png',
    'dial_code': '+244',
    'default_value': 'Angola',
  },
  {
    'index': 7,
    'code': 'AI',
    'flag': 'ai.png',
    'dial_code': '+1264',
    'default_value': 'Anguilla',
  },
  {
    'index': 8,
    'code': 'AQ',
    'flag': 'aq.png',
    'dial_code': '+672',
    'default_value': 'Antarctica',
  },
  {
    'index': 9,
    'code': 'AG',
    'flag': 'ag.png',
    'dial_code': '+1268',
    'default_value': 'Antigua and Barbuda',
  },
  {
    'index': 10,
    'code': 'AR',
    'flag': 'ar.png',
    'dial_code': '+54',
    'default_value': 'Argentina',
  },
  {
    'index': 11,
    'code': 'AM',
    'flag': 'am.png',
    'dial_code': '+374',
    'default_value': 'Armenia',
  },
  {
    'index': 12,
    'code': 'AW',
    'flag': 'aw.png',
    'dial_code': '+297',
    'default_value': 'Aruba',
  },
  {
    'index': 13,
    'code': 'AU',
    'flag': 'au.png',
    'dial_code': '+61',
    'default_value': 'Australia',
  },
  {
    'index': 14,
    'code': 'AT',
    'flag': 'at.png',
    'dial_code': '+43',
    'default_value': 'Austria',
  },
  {
    'index': 15,
    'code': 'AZ',
    'flag': 'az.png',
    'dial_code': '+994',
    'default_value': 'Azerbaijan',
  },
  {
    'index': 16,
    'code': 'BS',
    'flag': 'bs.png',
    'dial_code': '+1242',
    'default_value': 'Bahamas',
  },
  {
    'index': 17,
    'code': 'BH',
    'flag': 'bh.png',
    'dial_code': '+973',
    'default_value': 'Bahrain',
  },
  {
    'index': 18,
    'code': 'BD',
    'flag': 'bd.png',
    'dial_code': '+880',
    'default_value': 'Bangladesh',
  },
  {
    'index': 19,
    'code': 'BB',
    'flag': 'bb.png',
    'dial_code': '+1246',
    'default_value': 'Barbados',
  },
  {
    'index': 20,
    'code': 'BY',
    'flag': 'by.png',
    'dial_code': '+375',
    'default_value': 'Belarus',
  },
  {
    'index': 21,
    'code': 'BE',
    'flag': 'be.png',
    'dial_code': '+32',
    'default_value': 'Belgium',
  },
  {
    'index': 22,
    'code': 'BZ',
    'flag': 'bz.png',
    'dial_code': '+501',
    'default_value': 'Belize',
  },
  {
    'index': 23,
    'code': 'BJ',
    'flag': 'bj.png',
    'dial_code': '+229',
    'default_value': 'Benin',
  },
  {
    'index': 24,
    'code': 'BM',
    'flag': 'bm.png',
    'dial_code': '+1441',
    'default_value': 'Bermuda',
  },
  {
    'index': 25,
    'code': 'BT',
    'flag': 'bt.png',
    'dial_code': '+975',
    'default_value': 'Bhutan',
  },
  {
    'index': 26,
    'code': 'BO',
    'flag': 'bo.png',
    'dial_code': '+591',
    'default_value': 'Bolivia',
  },
  {
    'index': 27,
    'code': 'BA',
    'flag': 'ba.png',
    'dial_code': '+387',
    'default_value': 'Bosnia and Herzegovina',
  },
  {
    'index': 28,
    'code': 'BW',
    'flag': 'bw.png',
    'dial_code': '+267',
    'default_value': 'Botswana',
  },
  {
    'index': 29,
    'code': 'BV',
    'flag': 'bv.png',
    'dial_code': '+47',
    'default_value': 'Bouvet Island',
  },
  {
    'index': 30,
    'code': 'BR',
    'flag': 'br.png',
    'dial_code': '+55',
    'default_value': 'Brazil',
  },
  {
    'index': 31,
    'code': 'IO',
    'flag': 'io.png',
    'dial_code': '+246',
    'default_value': 'British Indian Ocean Territory',
  },
  {
    'index': 32,
    'code': 'BN',
    'flag': 'bn.png',
    'dial_code': '+673',
    'default_value': 'Brunei Darussalam',
  },
  {
    'index': 33,
    'code': 'BG',
    'flag': 'bg.png',
    'dial_code': '+359',
    'default_value': 'Bulgaria',
  },
  {
    'index': 34,
    'code': 'BF',
    'flag': 'bf.png',
    'dial_code': '+226',
    'default_value': 'Burkina Faso',
  },
  {
    'index': 35,
    'code': 'BI',
    'flag': 'bi.png',
    'dial_code': '+257',
    'default_value': 'Burundi',
  },
  {
    'index': 36,
    'code': 'KH',
    'flag': 'kh.png',
    'dial_code': '+855',
    'default_value': 'Cambodia',
  },
  {
    'index': 37,
    'code': 'CM',
    'flag': 'cm.png',
    'dial_code': '+237',
    'default_value': 'Cameroon',
  },
  {
    'index': 38,
    'code': 'CA',
    'flag': 'ca.png',
    'dial_code': '+1',
    'default_value': 'Canada',
  },
  {
    'index': 39,
    'code': 'CV',
    'flag': 'cv.png',
    'dial_code': '+238',
    'default_value': 'Cape Verde',
  },
  {
    'index': 40,
    'code': 'KY',
    'flag': 'ky.png',
    'dial_code': '+1345',
    'default_value': 'Cayman Islands',
  },
  {
    'index': 41,
    'code': 'CF',
    'flag': 'cf.png',
    'dial_code': '+236',
    'default_value': 'Central African Republic',
  },
  {
    'index': 42,
    'code': 'TD',
    'flag': 'td.png',
    'dial_code': '+235',
    'default_value': 'Chad',
  },
  {
    'index': 43,
    'code': 'CL',
    'flag': 'cl.png',
    'dial_code': '+56',
    'default_value': 'Chile',
  },
  {
    'index': 44,
    'code': 'CN',
    'flag': 'cn.png',
    'dial_code': '+86',
    'default_value': 'China',
  },
  {
    'index': 45,
    'code': 'CX',
    'flag': 'cx.png',
    'dial_code': '+61',
    'default_value': 'Christmas Island',
  },
  {
    'index': 46,
    'code': 'CC',
    'flag': 'cc.png',
    'dial_code': '+61',
    'default_value': 'Cocos (Keeling) Islands',
  },
  {
    'index': 47,
    'code': 'CO',
    'flag': 'co.png',
    'dial_code': '+57',
    'default_value': 'Colombia',
  },
  {
    'index': 48,
    'code': 'KM',
    'flag': 'km.png',
    'dial_code': '+269',
    'default_value': 'Comoros',
  },
  {
    'index': 49,
    'code': 'CG',
    'flag': 'cg.png',
    'dial_code': '+242',
    'default_value': 'Congo',
  },
  {
    'index': 50,
    'code': 'CD',
    'flag': 'cd.png',
    'dial_code': '+243',
    'default_value': 'Congo, the Democratic Republic of the',
  },
  {
    'index': 51,
    'code': 'CK',
    'flag': 'ck.png',
    'dial_code': '+682',
    'default_value': 'Cook Islands',
  },
  {
    'index': 52,
    'code': 'CR',
    'flag': 'cr.png',
    'dial_code': '+506',
    'default_value': 'Costa Rica',
  },
  {
    'index': 53,
    'code': 'CI',
    'flag': 'ci.png',
    'dial_code': '+225',
    'default_value': "Cote D'Ivoire",
  },
  {
    'index': 54,
    'code': 'HR',
    'flag': 'hr.png',
    'dial_code': '+385',
    'default_value': 'Croatia',
  },
  {
    'index': 55,
    'code': 'CU',
    'flag': 'cu.png',
    'dial_code': '+53',
    'default_value': 'Cuba',
  },
  {
    'index': 56,
    'code': 'CY',
    'flag': 'cy.png',
    'dial_code': '+357',
    'default_value': 'Cyprus',
  },
  {
    'index': 57,
    'code': 'CZ',
    'flag': 'cz.png',
    'dial_code': '+420',
    'default_value': 'Czech Republic',
  },
  {
    'index': 58,
    'code': 'DK',
    'flag': 'dk.png',
    'dial_code': '+45',
    'default_value': 'Denmark',
  },
  {
    'index': 59,
    'code': 'DJ',
    'flag': 'dj.png',
    'dial_code': '+253',
    'default_value': 'Djibouti',
  },
  {
    'index': 60,
    'code': 'DM',
    'flag': 'dm.png',
    'dial_code': '+1767',
    'default_value': 'Dominica',
  },
  {
    'index': 61,
    'code': 'DO',
    'flag': 'do.png',
    'dial_code': '+1',
    'default_value': 'Dominican Republic',
  },
  {
    'index': 62,
    'code': 'EC',
    'flag': 'ec.png',
    'dial_code': '+593',
    'default_value': 'Ecuador',
  },
  {
    'index': 63,
    'code': 'EG',
    'flag': 'eg.png',
    'dial_code': '+20',
    'default_value': 'Egypt',
  },
  {
    'index': 64,
    'code': 'SV',
    'flag': 'sv.png',
    'dial_code': '+503',
    'default_value': 'El Salvador',
  },
  {
    'index': 65,
    'code': 'GQ',
    'flag': 'gq.png',
    'dial_code': '+240',
    'default_value': 'Equatorial Guinea',
  },
  {
    'index': 66,
    'code': 'ER',
    'flag': 'er.png',
    'dial_code': '+291',
    'default_value': 'Eritrea',
  },
  {
    'index': 67,
    'code': 'EE',
    'flag': 'ee.png',
    'dial_code': '+372',
    'default_value': 'Estonia',
  },
  {
    'index': 68,
    'code': 'ET',
    'flag': 'et.png',
    'dial_code': '+251',
    'default_value': 'Ethiopia',
  },
  {
    'index': 69,
    'code': 'FK',
    'flag': 'fk.png',
    'dial_code': '+500',
    'default_value': 'Falkland Islands (Malvinas)',
  },
  {
    'index': 70,
    'code': 'FO',
    'flag': 'fo.png',
    'dial_code': '+298',
    'default_value': 'Faroe Islands',
  },
  {
    'index': 71,
    'code': 'FJ',
    'flag': 'fj.png',
    'dial_code': '+679',
    'default_value': 'Fiji',
  },
  {
    'index': 72,
    'code': 'FI',
    'flag': 'fi.png',
    'dial_code': '+358',
    'default_value': 'Finland',
  },
  {
    'index': 73,
    'code': 'FR',
    'flag': 'fr.png',
    'dial_code': '+33',
    'default_value': 'France',
  },
  {
    'index': 74,
    'code': 'GF',
    'flag': 'gf.png',
    'dial_code': '+594',
    'default_value': 'French Guiana',
  },
  {
    'index': 75,
    'code': 'PF',
    'flag': 'pf.png',
    'dial_code': '+689',
    'default_value': 'French Polynesia',
  },
  {
    'index': 76,
    'code': 'TF',
    'flag': 'tf.png',
    'dial_code': '+262',
    'default_value': 'French Southern Territories',
  },
  {
    'index': 77,
    'code': 'GA',
    'flag': 'ga.png',
    'dial_code': '+241',
    'default_value': 'Gabon',
  },
  {
    'index': 78,
    'code': 'GM',
    'flag': 'gm.png',
    'dial_code': '+220',
    'default_value': 'Gambia',
  },
  {
    'index': 79,
    'code': 'GE',
    'flag': 'ge.png',
    'dial_code': '+995',
    'default_value': 'Georgia',
  },
  {
    'index': 80,
    'code': 'DE',
    'flag': 'de.png',
    'dial_code': '+49',
    'default_value': 'Germany',
  },
  {
    'index': 81,
    'code': 'GH',
    'flag': 'gh.png',
    'dial_code': '+233',
    'default_value': 'Ghana',
  },
  {
    'index': 82,
    'code': 'GI',
    'flag': 'gi.png',
    'dial_code': '+350',
    'default_value': 'Gibraltar',
  },
  {
    'index': 83,
    'code': 'GR',
    'flag': 'gr.png',
    'dial_code': '+30',
    'default_value': 'Greece',
  },
  {
    'index': 84,
    'code': 'GL',
    'flag': 'gl.png',
    'dial_code': '+299',
    'default_value': 'Greenland',
  },
  {
    'index': 85,
    'code': 'GD',
    'flag': 'gd.png',
    'dial_code': '+1473',
    'default_value': 'Grenada',
  },
  {
    'index': 86,
    'code': 'GP',
    'flag': 'gp.png',
    'dial_code': '+590',
    'default_value': 'Guadeloupe',
  },
  {
    'index': 87,
    'code': 'GU',
    'flag': 'gu.png',
    'dial_code': '+1671',
    'default_value': 'Guam',
  },
  {
    'index': 88,
    'code': 'GT',
    'flag': 'gt.png',
    'dial_code': '+502',
    'default_value': 'Guatemala',
  },
  {
    'index': 89,
    'code': 'GG',
    'flag': 'gg.png',
    'dial_code': '+44',
    'default_value': 'Guernsey',
  },
  {
    'index': 90,
    'code': 'GN',
    'flag': 'gn.png',
    'dial_code': '+224',
    'default_value': 'Guinea',
  },
  {
    'index': 91,
    'code': 'GW',
    'flag': 'gw.png',
    'dial_code': '+245',
    'default_value': 'Guinea-Bissau',
  },
  {
    'index': 92,
    'code': 'GY',
    'flag': 'gy.png',
    'dial_code': '+592',
    'default_value': 'Guyana',
  },
  {
    'index': 93,
    'code': 'HT',
    'flag': 'ht.png',
    'dial_code': '+509',
    'default_value': 'Haiti',
  },
  {
    'index': 94,
    'code': 'HM',
    'flag': 'hm.png',
    'dial_code': '+0',
    'default_value': 'Heard Island and McDonald Islands',
  },
  {
    'index': 95,
    'code': 'VA',
    'flag': 'va.png',
    'dial_code': '+379',
    'default_value': 'Holy See (Vatican City State)',
  },
  {
    'index': 96,
    'code': 'HN',
    'flag': 'hn.png',
    'dial_code': '+504',
    'default_value': 'Honduras',
  },
  {
    'index': 97,
    'code': 'HK',
    'flag': 'hk.png',
    'dial_code': '+852',
    'default_value': 'Hong Kong',
  },
  {
    'index': 98,
    'code': 'HU',
    'flag': 'hu.png',
    'dial_code': '+36',
    'default_value': 'Hungary',
  },
  {
    'index': 99,
    'code': 'IS',
    'flag': 'is.png',
    'dial_code': '+354',
    'default_value': 'Iceland',
  },
  {
    'index': 100,
    'code': 'IN',
    'flag': 'in.png',
    'dial_code': '+91',
    'default_value': 'India',
  },
  {
    'index': 101,
    'code': 'ID',
    'flag': 'id.png',
    'dial_code': '+62',
    'default_value': 'Indonesia',
  },
  {
    'index': 102,
    'code': 'IR',
    'flag': 'ir.png',
    'dial_code': '+98',
    'default_value': 'Iran, Islamic Republic of',
  },
  {
    'index': 103,
    'code': 'IQ',
    'flag': 'iq.png',
    'dial_code': '+964',
    'default_value': 'Iraq',
  },
  {
    'index': 104,
    'code': 'IE',
    'flag': 'ie.png',
    'dial_code': '+353',
    'default_value': 'Ireland',
  },
  {
    'index': 105,
    'code': 'IM',
    'flag': 'im.png',
    'dial_code': '+44',
    'default_value': 'Isle of Man',
  },
  {
    'index': 106,
    'code': 'IL',
    'flag': 'il.png',
    'dial_code': '+972',
    'default_value': 'Israel',
  },
  {
    'index': 107,
    'code': 'IT',
    'flag': 'it.png',
    'dial_code': '+39',
    'default_value': 'Italy',
  },
  {
    'index': 108,
    'code': 'JM',
    'flag': 'jm.png',
    'dial_code': '+1876',
    'default_value': 'Jamaica',
  },
  {
    'index': 109,
    'code': 'JP',
    'flag': 'jp.png',
    'dial_code': '+81',
    'default_value': 'Japan',
  },
  {
    'index': 110,
    'code': 'JE',
    'flag': 'je.png',
    'dial_code': '+44',
    'default_value': 'Jersey',
  },
  {
    'index': 111,
    'code': 'JO',
    'flag': 'jo.png',
    'dial_code': '+962',
    'default_value': 'Jordan',
  },
  {
    'index': 112,
    'code': 'KZ',
    'flag': 'kz.png',
    'dial_code': '+7',
    'default_value': 'Kazakhstan',
  },
  {
    'index': 113,
    'code': 'KE',
    'flag': 'ke.png',
    'dial_code': '+254',
    'default_value': 'Kenya',
  },
  {
    'index': 114,
    'code': 'KI',
    'flag': 'ki.png',
    'dial_code': '+686',
    'default_value': 'Kiribati',
  },
  {
    'index': 115,
    'code': 'KP',
    'flag': 'kp.png',
    'dial_code': '+850',
    'default_value': 'North Korea',
  },
  {
    'index': 116,
    'code': 'KR',
    'flag': 'kr.png',
    'dial_code': '+82',
    'default_value': 'South Korea',
  },
  {
    'index': 117,
    'code': 'XK',
    'flag': 'xk.png',
    'dial_code': '+383',
    'default_value': 'Kosovo',
  },
  {
    'index': 118,
    'code': 'KW',
    'flag': 'kw.png',
    'dial_code': '+965',
    'default_value': 'Kuwait',
  },
  {
    'index': 119,
    'code': 'KG',
    'flag': 'kg.png',
    'dial_code': '+996',
    'default_value': 'Kyrgyzstan',
  },
  {
    'index': 120,
    'code': 'LA',
    'flag': 'la.png',
    'dial_code': '+856',
    'default_value': "Lao People's Democratic Republic",
  },
  {
    'index': 121,
    'code': 'LV',
    'flag': 'lv.png',
    'dial_code': '+371',
    'default_value': 'Latvia',
  },
  {
    'index': 122,
    'code': 'LB',
    'flag': 'lb.png',
    'dial_code': '+961',
    'default_value': 'Lebanon',
  },
  {
    'index': 123,
    'code': 'LS',
    'flag': 'ls.png',
    'dial_code': '+266',
    'default_value': 'Lesotho',
  },
  {
    'index': 124,
    'code': 'LR',
    'flag': 'lr.png',
    'dial_code': '+231',
    'default_value': 'Liberia',
  },
  {
    'index': 125,
    'code': 'LY',
    'flag': 'ly.png',
    'dial_code': '+218',
    'default_value': 'Libya',
  },
  {
    'index': 126,
    'code': 'LI',
    'flag': 'li.png',
    'dial_code': '+423',
    'default_value': 'Liechtenstein',
  },
  {
    'index': 127,
    'code': 'LT',
    'flag': 'lt.png',
    'dial_code': '+370',
    'default_value': 'Lithuania',
  },
  {
    'index': 128,
    'code': 'LU',
    'flag': 'lu.png',
    'dial_code': '+352',
    'default_value': 'Luxembourg',
  },
  {
    'index': 129,
    'code': 'MO',
    'flag': 'mo.png',
    'dial_code': '+853',
    'default_value': 'Macao',
  },
  {
    'index': 130,
    'code': 'MK',
    'flag': 'mk.png',
    'dial_code': '+389',
    'default_value': 'North Macedonia, Republic of',
  },
  {
    'index': 131,
    'code': 'MG',
    'flag': 'mg.png',
    'dial_code': '+261',
    'default_value': 'Madagascar',
  },
  {
    'index': 132,
    'code': 'MW',
    'flag': 'mw.png',
    'dial_code': '+265',
    'default_value': 'Malawi',
  },
  {
    'index': 133,
    'code': 'MY',
    'flag': 'my.png',
    'dial_code': '+60',
    'default_value': 'Malaysia',
  },
  {
    'index': 134,
    'code': 'MV',
    'flag': 'mv.png',
    'dial_code': '+960',
    'default_value': 'Maldives',
  },
  {
    'index': 135,
    'code': 'ML',
    'flag': 'ml.png',
    'dial_code': '+223',
    'default_value': 'Mali',
  },
  {
    'index': 136,
    'code': 'MT',
    'flag': 'mt.png',
    'dial_code': '+356',
    'default_value': 'Malta',
  },
  {
    'index': 137,
    'code': 'MH',
    'flag': 'mh.png',
    'dial_code': '+692',
    'default_value': 'Marshall Islands',
  },
  {
    'index': 138,
    'code': 'MQ',
    'flag': 'mq.png',
    'dial_code': '+596',
    'default_value': 'Martinique',
  },
  {
    'index': 139,
    'code': 'MR',
    'flag': 'mr.png',
    'dial_code': '+222',
    'default_value': 'Mauritania',
  },
  {
    'index': 140,
    'code': 'MU',
    'flag': 'mu.png',
    'dial_code': '+230',
    'default_value': 'Mauritius',
  },
  {
    'index': 141,
    'code': 'YT',
    'flag': 'yt.png',
    'dial_code': '+262',
    'default_value': 'Mayotte',
  },
  {
    'index': 142,
    'code': 'MX',
    'flag': 'mx.png',
    'dial_code': '+52',
    'default_value': 'Mexico',
  },
  {
    'index': 143,
    'code': 'FM',
    'flag': 'fm.png',
    'dial_code': '+691',
    'default_value': 'Micronesia, Federated States of',
  },
  {
    'index': 144,
    'code': 'MD',
    'flag': 'md.png',
    'dial_code': '+373',
    'default_value': 'Moldova, Republic of',
  },
  {
    'index': 145,
    'code': 'MC',
    'flag': 'mc.png',
    'dial_code': '+377',
    'default_value': 'Monaco',
  },
  {
    'index': 146,
    'code': 'MN',
    'flag': 'mn.png',
    'dial_code': '+976',
    'default_value': 'Mongolia',
  },
  {
    'index': 147,
    'code': 'ME',
    'flag': 'me.png',
    'dial_code': '+382',
    'default_value': 'Montenegro',
  },
  {
    'index': 148,
    'code': 'MS',
    'flag': 'ms.png',
    'dial_code': '+1664',
    'default_value': 'Montserrat',
  },
  {
    'index': 149,
    'code': 'MA',
    'flag': 'ma.png',
    'dial_code': '+212',
    'default_value': 'Morocco',
  },
  {
    'index': 150,
    'code': 'MZ',
    'flag': 'mz.png',
    'dial_code': '+258',
    'default_value': 'Mozambique',
  },
  {
    'index': 151,
    'code': 'MM',
    'flag': 'mm.png',
    'dial_code': '+95',
    'default_value': 'Myanmar',
  },
  {
    'index': 152,
    'code': 'NA',
    'flag': 'na.png',
    'dial_code': '+264',
    'default_value': 'Namibia',
  },
  {
    'index': 153,
    'code': 'NR',
    'flag': 'nr.png',
    'dial_code': '+674',
    'default_value': 'Nauru',
  },
  {
    'index': 154,
    'code': 'NP',
    'flag': 'np.png',
    'dial_code': '+977',
    'default_value': 'Nepal',
  },
  {
    'index': 155,
    'code': 'NL',
    'flag': 'nl.png',
    'dial_code': '+31',
    'default_value': 'Netherlands',
  },
  {
    'index': 156,
    'code': 'AN',
    'flag': 'an.png',
    'dial_code': '+599',
    'default_value': 'Netherlands Antilles',
  },
  {
    'index': 157,
    'code': 'NC',
    'flag': 'nc.png',
    'dial_code': '+687',
    'default_value': 'New Caledonia',
  },
  {
    'index': 158,
    'code': 'NZ',
    'flag': 'nz.png',
    'dial_code': '+64',
    'default_value': 'New Zealand',
  },
  {
    'index': 159,
    'code': 'NI',
    'flag': 'ni.png',
    'dial_code': '+505',
    'default_value': 'Nicaragua',
  },
  {
    'index': 160,
    'code': 'NE',
    'flag': 'ne.png',
    'dial_code': '+227',
    'default_value': 'Niger',
  },
  {
    'index': 161,
    'code': 'NG',
    'flag': 'ng.png',
    'dial_code': '+234',
    'default_value': 'Nigeria',
  },
  {
    'index': 162,
    'code': 'NU',
    'flag': 'nu.png',
    'dial_code': '+683',
    'default_value': 'Niue',
  },
  {
    'index': 163,
    'code': 'NF',
    'flag': 'nf.png',
    'dial_code': '+672',
    'default_value': 'Norfolk Island',
  },
  {
    'index': 164,
    'code': 'MP',
    'flag': 'mp.png',
    'dial_code': '+1670',
    'default_value': 'Northern Mariana Islands',
  },
  {
    'index': 165,
    'code': 'NO',
    'flag': 'no.png',
    'dial_code': '+47',
    'default_value': 'Norway',
  },
  {
    'index': 166,
    'code': 'OM',
    'flag': 'om.png',
    'dial_code': '+968',
    'default_value': 'Oman',
  },
  {
    'index': 167,
    'code': 'PK',
    'flag': 'pk.png',
    'dial_code': '+92',
    'default_value': 'Pakistan',
  },
  {
    'index': 168,
    'code': 'PW',
    'flag': 'pw.png',
    'dial_code': '+680',
    'default_value': 'Palau',
  },
  {
    'index': 169,
    'code': 'PS',
    'flag': 'ps.png',
    'dial_code': '+970',
    'default_value': 'Palestine',
  },
  {
    'index': 170,
    'code': 'PA',
    'flag': 'pa.png',
    'dial_code': '+507',
    'default_value': 'Panama',
  },
  {
    'index': 171,
    'code': 'PG',
    'flag': 'pg.png',
    'dial_code': '+675',
    'default_value': 'Papua New Guinea',
  },
  {
    'index': 172,
    'code': 'PY',
    'flag': 'py.png',
    'dial_code': '+595',
    'default_value': 'Paraguay',
  },
  {
    'index': 173,
    'code': 'PE',
    'flag': 'pe.png',
    'dial_code': '+51',
    'default_value': 'Peru',
  },
  {
    'index': 174,
    'code': 'PH',
    'flag': 'ph.png',
    'dial_code': '+63',
    'default_value': 'Philippines',
  },
  {
    'index': 175,
    'code': 'PN',
    'flag': 'pn.png',
    'dial_code': '+64',
    'default_value': 'Pitcairn',
  },
  {
    'index': 176,
    'code': 'PL',
    'flag': 'pl.png',
    'dial_code': '+48',
    'default_value': 'Poland',
  },
  {
    'index': 177,
    'code': 'PT',
    'flag': 'pt.png',
    'dial_code': '+351',
    'default_value': 'Portugal',
  },
  {
    'index': 178,
    'code': 'PR',
    'flag': 'pr.png',
    'dial_code': '+1939',
    'default_value': 'Puerto Rico',
  },
  {
    'index': 179,
    'code': 'PR',
    'flag': 'pr.png',
    'dial_code': '+1787',
    'default_value': 'Puerto Rico',
  },
  {
    'index': 180,
    'code': 'QA',
    'flag': 'qa.png',
    'dial_code': '+974',
    'default_value': 'Qatar',
  },
  {
    'index': 181,
    'code': 'RO',
    'flag': 'ro.png',
    'dial_code': '+40',
    'default_value': 'Romania',
  },
  {
    'index': 182,
    'code': 'RU',
    'flag': 'ru.png',
    'dial_code': '+7',
    'default_value': 'Russia',
  },
  {
    'index': 183,
    'code': 'RW',
    'flag': 'rw.png',
    'dial_code': '+250',
    'default_value': 'Rwanda',
  },
  {
    'index': 184,
    'code': 'RE',
    'flag': 're.png',
    'dial_code': '+262',
    'default_value': 'Reunion',
  },
  {
    'index': 185,
    'code': 'BL',
    'flag': 'bl.png',
    'dial_code': '+590',
    'default_value': 'Saint Barthélemy',
  },
  {
    'index': 186,
    'code': 'SH',
    'flag': 'sh.png',
    'dial_code': '+290',
    'default_value': 'Saint Helena',
  },
  {
    'index': 187,
    'code': 'KN',
    'flag': 'kn.png',
    'dial_code': '+1869',
    'default_value': 'Saint Kitts and Nevis',
  },
  {
    'index': 188,
    'code': 'LC',
    'flag': 'lc.png',
    'dial_code': '+1758',
    'default_value': 'Saint Lucia',
  },
  {
    'index': 189,
    'code': 'MF',
    'flag': 'mf.png',
    'dial_code': '+590',
    'default_value': 'Saint Martin (French part)',
  },
  {
    'index': 190,
    'code': 'PM',
    'flag': 'pm.png',
    'dial_code': '+508',
    'default_value': 'Saint Pierre and Miquelon',
  },
  {
    'index': 191,
    'code': 'VC',
    'flag': 'vc.png',
    'dial_code': '+1784',
    'default_value': 'Saint Vincent and the Grenadines',
  },
  {
    'index': 192,
    'code': 'WS',
    'flag': 'ws.png',
    'dial_code': '+685',
    'default_value': 'Samoa',
  },
  {
    'index': 193,
    'code': 'SM',
    'flag': 'sm.png',
    'dial_code': '+378',
    'default_value': 'San Marino',
  },
  {
    'index': 194,
    'code': 'ST',
    'flag': 'st.png',
    'dial_code': '+239',
    'default_value': 'Sao Tome and Principe',
  },
  {
    'index': 195,
    'code': 'SA',
    'flag': 'sa.png',
    'dial_code': '+966',
    'default_value': 'Saudi Arabia',
  },
  {
    'index': 196,
    'code': 'SN',
    'flag': 'sn.png',
    'dial_code': '+221',
    'default_value': 'Senegal',
  },
  {
    'index': 197,
    'code': 'RS',
    'flag': 'rs.png',
    'dial_code': '+381',
    'default_value': 'Serbia',
  },
  {
    'index': 198,
    'code': 'SC',
    'flag': 'sc.png',
    'dial_code': '+248',
    'default_value': 'Seychelles',
  },
  {
    'index': 199,
    'code': 'SL',
    'flag': 'sl.png',
    'dial_code': '+232',
    'default_value': 'Sierra Leone',
  },
  {
    'index': 200,
    'code': 'SG',
    'flag': 'sg.png',
    'dial_code': '+65',
    'default_value': 'Singapore',
  },
  {
    'index': 201,
    'code': 'SK',
    'flag': 'sk.png',
    'dial_code': '+421',
    'default_value': 'Slovakia',
  },
  {
    'index': 202,
    'code': 'SI',
    'flag': 'si.png',
    'dial_code': '+386',
    'default_value': 'Slovenia',
  },
  {
    'index': 203,
    'code': 'SB',
    'flag': 'sb.png',
    'dial_code': '+677',
    'default_value': 'Solomon Islands',
  },
  {
    'index': 204,
    'code': 'SO',
    'flag': 'so.png',
    'dial_code': '+252',
    'default_value': 'Somalia',
  },
  {
    'index': 205,
    'code': 'ZA',
    'flag': 'za.png',
    'dial_code': '+27',
    'default_value': 'South Africa',
  },
  {
    'index': 206,
    'code': 'SS',
    'flag': 'ss.png',
    'dial_code': '+211',
    'default_value': 'South Sudan',
  },
  {
    'index': 207,
    'code': 'GS',
    'flag': 'gs.png',
    'dial_code': '+500',
    'default_value': 'South Georgia and the South Sandwich Islands ',
  },
  {
    'index': 208,
    'code': 'ES',
    'flag': 'es.png',
    'dial_code': '+34',
    'default_value': 'Spain',
  },
  {
    'index': 209,
    'code': 'LK',
    'flag': 'lk.png',
    'dial_code': '+94',
    'default_value': 'Sri Lanka',
  },
  {
    'index': 210,
    'code': 'SD',
    'flag': 'sd.png',
    'dial_code': '+249',
    'default_value': 'Sudan',
  },
  {
    'index': 211,
    'code': 'SR',
    'flag': 'sr.png',
    'dial_code': '+597',
    'default_value': 'Suriname',
  },
  {
    'index': 212,
    'code': 'SJ',
    'flag': 'sj.png',
    'dial_code': '+47',
    'default_value': 'Svalbard and Jan Mayen',
  },
  {
    'index': 213,
    'code': 'SZ',
    'flag': 'sz.png',
    'dial_code': '+268',
    'default_value': 'Eswatini',
  },
  {
    'index': 214,
    'code': 'SE',
    'flag': 'se.png',
    'dial_code': '+46',
    'default_value': 'Sweden',
  },
  {
    'index': 215,
    'code': 'CH',
    'flag': 'ch.png',
    'dial_code': '+41',
    'default_value': 'Switzerland',
  },
  {
    'index': 216,
    'code': 'SY',
    'flag': 'sy.png',
    'dial_code': '+963',
    'default_value': 'Syrian Arab Republic',
  },
  {
    'index': 217,
    'code': 'TW',
    'flag': 'tw.png',
    'dial_code': '+886',
    'default_value': 'Taiwan',
  },
  {
    'index': 218,
    'code': 'TJ',
    'flag': 'tj.png',
    'dial_code': '+992',
    'default_value': 'Tajikistan',
  },
  {
    'index': 219,
    'code': 'TZ',
    'flag': 'tz.png',
    'dial_code': '+255',
    'default_value': 'Tanzania, United Republic of',
  },
  {
    'index': 220,
    'code': 'TH',
    'flag': 'th.png',
    'dial_code': '+66',
    'default_value': 'Thailand',
  },
  {
    'index': 221,
    'code': 'TL',
    'flag': 'tl.png',
    'dial_code': '+670',
    'default_value': 'Timor-Leste',
  },
  {
    'index': 222,
    'code': 'TG',
    'flag': 'tg.png',
    'dial_code': '+228',
    'default_value': 'Togo',
  },
  {
    'index': 223,
    'code': 'TK',
    'flag': 'tk.png',
    'dial_code': '+690',
    'default_value': 'Tokelau',
  },
  {
    'index': 224,
    'code': 'TO',
    'flag': 'to.png',
    'dial_code': '+676',
    'default_value': 'Tonga',
  },
  {
    'index': 225,
    'code': 'TT',
    'flag': 'tt.png',
    'dial_code': '+1868',
    'default_value': 'Trinidad and Tobago',
  },
  {
    'index': 226,
    'code': 'TN',
    'flag': 'tn.png',
    'dial_code': '+216',
    'default_value': 'Tunisia',
  },
  {
    'index': 227,
    'code': 'TR',
    'flag': 'tr.png',
    'dial_code': '+90',
    'default_value': 'Türkiye',
  },
  {
    'index': 228,
    'code': 'TM',
    'flag': 'tm.png',
    'dial_code': '+993',
    'default_value': 'Turkmenistan',
  },
  {
    'index': 229,
    'code': 'TC',
    'flag': 'tc.png',
    'dial_code': '+1649',
    'default_value': 'Turks and Caicos Islands',
  },
  {
    'index': 230,
    'code': 'TV',
    'flag': 'tv.png',
    'dial_code': '+688',
    'default_value': 'Tuvalu',
  },
  {
    'index': 231,
    'code': 'UG',
    'flag': 'ug.png',
    'dial_code': '+256',
    'default_value': 'Uganda',
  },
  {
    'index': 232,
    'code': 'UA',
    'flag': 'ua.png',
    'dial_code': '+380',
    'default_value': 'Ukraine',
  },
  {
    'index': 233,
    'code': 'AE',
    'flag': 'ae.png',
    'dial_code': '+971',
    'default_value': 'United Arab Emirates',
  },
  {
    'index': 234,
    'code': 'GB',
    'flag': 'gb.png',
    'dial_code': '+44',
    'default_value': 'United Kingdom',
  },
  {
    'index': 235,
    'code': 'US',
    'flag': 'us.png',
    'dial_code': '+1',
    'default_value': 'United States of America',
  },
  {
    'index': 236,
    'code': 'UY',
    'flag': 'uy.png',
    'dial_code': '+598',
    'default_value': 'Uruguay',
  },
  {
    'index': 237,
    'code': 'UZ',
    'flag': 'uz.png',
    'dial_code': '+998',
    'default_value': 'Uzbekistan',
  },
  {
    'index': 238,
    'code': 'VU',
    'flag': 'vu.png',
    'dial_code': '+678',
    'default_value': 'Vanuatu',
  },
  {
    'index': 239,
    'code': 'VE',
    'flag': 've.png',
    'dial_code': '+58',
    'default_value': 'Venezuela',
  },
  {
    'index': 240,
    'code': 'VN',
    'flag': 'vn.png',
    'dial_code': '+84',
    'default_value': 'Vietnam',
  },
  {
    'index': 241,
    'code': 'VG',
    'flag': 'vg.png',
    'dial_code': '+1284',
    'default_value': 'Virgin Islands, British',
  },
  {
    'index': 242,
    'code': 'VI',
    'flag': 'vi.png',
    'dial_code': '+1340',
    'default_value': 'Virgin Islands, U.S.',
  },
  {
    'index': 243,
    'code': 'WF',
    'flag': 'wf.png',
    'dial_code': '+681',
    'default_value': 'Wallis and Futuna',
  },
  {
    'index': 244,
    'code': 'YE',
    'flag': 'ye.png',
    'dial_code': '+967',
    'default_value': 'Yemen',
  },
  {
    'index': 245,
    'code': 'ZM',
    'flag': 'zm.png',
    'dial_code': '+260',
    'default_value': 'Zambia',
  },
  {
    'index': 246,
    'code': 'ZW',
    'flag': 'zw.png',
    'dial_code': '+263',
    'default_value': 'Zimbabwe',
  },
];
